//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discuz.Web.Admin {
    
    
    public partial class option {
        
        /// <summary>
        /// form1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm Form1;
        
        /// <summary>
        /// Topicqueuestats_1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputRadioButton Topicqueuestats_1;
        
        /// <summary>
        /// Topicqueuestats_0 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputRadioButton Topicqueuestats_0;
        
        /// <summary>
        /// topicqueuestatscount 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.TextBox topicqueuestatscount;
        
        /// <summary>
        /// userstatusby 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList userstatusby;
        
        /// <summary>
        /// statstatus 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList statstatus;
        
        /// <summary>
        /// statscachelife 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.TextBox statscachelife;
        
        /// <summary>
        /// maxmodworksmonths 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.TextBox maxmodworksmonths;
        
        /// <summary>
        /// guestcachepagetimeout 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.TextBox guestcachepagetimeout;
        
        /// <summary>
        /// reasonpm 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList reasonpm;
        
        /// <summary>
        /// edittimelimit 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.TextBox edittimelimit;
        
        /// <summary>
        /// tpp 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.TextBox tpp;
        
        /// <summary>
        /// hottopic 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.TextBox hottopic;
        
        /// <summary>
        /// enabletag 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList enabletag;
        
        /// <summary>
        /// hottagcount 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.TextBox hottagcount;
        
        /// <summary>
        /// fastpost 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList fastpost;
        
        /// <summary>
        /// allowhtmltitle 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList allowhtmltitle;
        
        /// <summary>
        /// modworkstatus 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList modworkstatus;
        
        /// <summary>
        /// oltimespan 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.TextBox oltimespan;
        
        /// <summary>
        /// topiccachemark 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.TextBox topiccachemark;
        
        /// <summary>
        /// losslessdel 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.TextBox losslessdel;
        
        /// <summary>
        /// editedby 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList editedby;
        
        /// <summary>
        /// ppp 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.TextBox ppp;
        
        /// <summary>
        /// starthreshold 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.TextBox starthreshold;
        
        /// <summary>
        /// defaulteditormode 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList defaulteditormode;
        
        /// <summary>
        /// allowswitcheditor 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList allowswitcheditor;
        
        /// <summary>
        /// ratevalveset1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.TextBox ratevalveset1;
        
        /// <summary>
        /// ratevalveset2 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.TextBox ratevalveset2;
        
        /// <summary>
        /// ratevalveset3 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.TextBox ratevalveset3;
        
        /// <summary>
        /// ratevalveset4 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.TextBox ratevalveset4;
        
        /// <summary>
        /// ratevalveset5 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.TextBox ratevalveset5;
        
        /// <summary>
        /// Hint1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.Hint Hint1;

        /// <summary>
        /// replypostssendmessage 控件
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList replynotificationstatus;

        /// <summary>
        /// replypostssendmail 控件
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList replyemailstatus;

        /// <summary>
        /// allowforumindexposts
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList allowforumindexposts;

        /// <summary>
        /// SaveInfo 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.Button SaveInfo;
        
        /// <summary>
        /// fullmytopics 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList fullmytopics;
        protected global::Discuz.Control.RadioButtonList disablepostad;
        protected global::Discuz.Control.TextBox disablepostadregminute;
        protected global::Discuz.Control.TextBox disablepostadpostcount;
        protected global::Discuz.Web.Admin.TextareaResize disablepostadregular;
        protected System.Web.UI.HtmlControls.HtmlControl postadstatus;
    }
}
