//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discuz.Web.Admin
{


    public partial class uiandshowstyle
    {

        /// <summary>
        /// Form1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm Form1;

        /// <summary>
        /// Hint1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.Hint Hint1;

        /// <summary>
        /// templateid 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.DropDownList templateid;

        /// <summary>
        /// browsecreatetemplate 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList browsecreatetemplate;

        /// <summary>
        /// stylejump 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList stylejump;

        /// <summary>
        /// visitedforums 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.TextBox visitedforums;

        /// <summary>
        /// maxsigrows 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.TextBox maxsigrows;

        /// <summary>
        /// showsignatures 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList showsignatures;

        /// <summary>
        /// showimages 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList showimages;

        /// <summary>
        /// smileyinsert 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList smileyinsert;

        /// <summary>
        /// showauthorstatusinpost 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList showauthorstatusinpost;

        /// <summary>
        /// forumjump 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList forumjump;

        /// <summary>
        /// viewnewtopicminute 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.TextBox viewnewtopicminute;

        /// <summary>
        /// isframeshow 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList isframeshow;

        /// <summary>
        /// preview 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlImage preview;

        /// <summary>
        /// moddisplay 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList moddisplay;

        /// <summary>
        /// showavatars 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList showavatars;


        /// <summary>
        /// allowfloatwin控件
        /// </summary>
        /// <remarks>
        ///自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList allowfloatwin;

        /// <summary>
        /// smiliesmax 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.TextBox smiliesmax;

        /// <summary>
        /// whosonlinestatus 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList whosonlinestatus;

        /// <summary>
        /// maxonlinelist 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.TextBox maxonlinelist;

        /// <summary>
        /// onlinetimeout 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.TextBox onlinetimeout;

        /// <summary>
        /// SaveInfo 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.Button SaveInfo;

        /// <summary>
        /// browsecreatetemplate 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Discuz.Control.RadioButtonList whosonlinecontact;
        protected global::Discuz.Web.Admin.TextareaResize postnocustom;
        protected global::Discuz.Control.RadioButtonList quickforward;
        protected global::Discuz.Web.Admin.TextareaResize msgforwardlist;
        protected global::Discuz.Control.RadioButtonList openshare;
        protected global::Discuz.Control.RadioButtonList shownewposticon;
    }
}
